"""criar tabela de embeddings

Revision ID: 87073c4790c2
Revises: 139739afec84
Create Date: 2026-05-30 11:07:15.926759

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87073c4790c2'
down_revision: Union[str, Sequence[str], None] = '139739afec84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding_document')
    # ### end Alembic commands ###
