"""atualizar workout e criar exercise e workout_exercise

Revision ID: c3a0d90cff64
Revises: 87073c4790c2
Create Date: 2026-05-30 12:05:10.037305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c3a0d90cff64'
down_revision: Union[str, Sequence[str], None] = '87073c4790c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('muscle_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('workout_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercise_exercise_id'), 'workout_exercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_workout_id'), 'workout_exercise', ['workout_id'], unique=False)
    op.add_column('workout', sa.Column('main_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('workout', sa.Column('workout_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('workout', sa.Column('training_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=False))
    op.add_column('workout', sa.Column('program_duration_weeks', sa.Integer(), nullable=True))
    op.add_column('workout', sa.Column('days_per_week', sa.Integer(), nullable=True))
    op.add_column('workout', sa.Column('time_per_workout', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workout', sa.Column('equipment_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workout', sa.Column('target_gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('workout', 'difficulty_level')
    op.drop_column('workout', 'estimated_duration_minutes')
    op.drop_column('workout', 'objective')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('objective', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('difficulty_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficultylevel'), autoincrement=False, nullable=False))
    op.drop_column('workout', 'target_gender')
    op.drop_column('workout', 'equipment_required')
    op.drop_column('workout', 'time_per_workout')
    op.drop_column('workout', 'days_per_week')
    op.drop_column('workout', 'program_duration_weeks')
    op.drop_column('workout', 'training_level')
    op.drop_column('workout', 'workout_type')
    op.drop_column('workout', 'main_goal')
    op.drop_index(op.f('ix_workout_exercise_workout_id'), table_name='workout_exercise')
    op.drop_index(op.f('ix_workout_exercise_exercise_id'), table_name='workout_exercise')
    op.drop_table('workout_exercise')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
